### PR TITLE
Patch/nightly build failed upgrade yarn

### LINKED ISSUE #353: Nightly build fails
The nightly build is failing. I attempted to `yarn install` on my Mac, and it still worked. I tested this on my Ubuntu machine and it failed. The linux dependencies are not aligning on the install on Linux machines.

image

Since the Github Actions `nightly.yaml` file uses Ubuntu, this is likely why it is failing in the nightly run.

image

I re-created the issue on my local Linux machine here: 

```
ubuntu@gothboots:~/relay-starter-kit$ yarn
➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: ┌ Resolution step
a➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [f3640] doesn't provide typescript (p07f79), requested by ts-node
➤ YN0002: │ @types/webpack-dev-server@npm:4.7.2 doesn't provide webpack (p8da21), requested by webpack-dev-server
➤ YN0002: │ app@workspace:. doesn't provide graphql (pf8a9e), requested by graphql-config
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 500ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.5.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ youch@npm:2.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zx@npm:6.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 50s 430ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ app@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.22.5 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.22.5 must be built because it never has been before or the last one failed
➤ YN0007: │ argon2@npm:0.28.5 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.34 must be built because it never has been before or the last one failed
➤ YN0009: │ app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-d05e955a/build.log)
➤ YN0009: │ esbuild@npm:0.14.34 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-a59ec998/build.log)
➤ YN0009: │ argon2@npm:0.28.5 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-a6be60d9/build.log)
➤ YN0000: └ Completed in 6s 330ms
➤ YN0000: Failed with errors in 57s 872ms
```

### PR DESCRIPTION
**Pull request by andrewstec**
Closes #353

@koistya If there is a way to test the nightly build just by waiting, let's do that. I only did some very basic testing to see that I can `yarn install` and `yarn start`. 

## Yarn install fixed in the first commit with a yarn upgrade: 

```
ubuntu@gothboots:~/andrew-relay-starter-kit$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [f3640] doesn't provide typescript (p07f79), requested by ts-node
➤ YN0002: │ @types/webpack-dev-server@npm:4.7.2 doesn't provide webpack (p8da21), requested by webpack-dev-server
➤ YN0002: │ app@workspace:. doesn't provide graphql (pf8a9e), requested by graphql-config
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 915ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.5.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ youch@npm:2.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zx@npm:6.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 4s 259ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ app@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ argon2@npm:0.28.5 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.34 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3s 964ms
➤ YN0000: Done with warnings in 9s 586ms
```

## Then `yarn start` breaks after the upgrade so we need to add the `foreach` module in the second commit:

```
ubuntu@gothboots:~/andrew-relay-starter-kit$ yarn run start
➤ YN0000: rollup v2.75.5
➤ YN0000: bundles ./index.ts → dist...
➤ YN0000: <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
➤ YN0000: <i> [webpack-dev-server] [HPM] Proxy created: /api,/auth  -> http://localhost:8080
➤ YN0000: <i> [webpack-dev-server] Project is running at:
➤ YN0000: <i> [webpack-dev-server] Loopback: http://localhost:3000/
➤ YN0000: <i> [webpack-dev-server] On Your Network (IPv4): http://10.0.0.192:3000/
➤ YN0000: <i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::20f:feff:fef4:d4e3]:3000/
➤ YN0000: <i> [webpack-dev-server] Content not from webpack is served from './public' directory
➤ YN0000: <i> [webpack-dev-server] 404s will fallback to '/index.html'

```

## The build was also breaking with the new foreach module plugin, and had to be copied in the third commit to be included in the rollup configuration:

```
ubuntu@gothboots:~/andrew-relay-starter-kit$ yarn run build
➤ YN0000: ➤ YN0000: Successfully set enableGlobalCache to false
➤ YN0000: ➤ YN0000: ┌ Resolution step
➤ YN0000: ➤ YN0000: └ Completed in 0s 241ms
➤ YN0000: ➤ YN0000: ┌ Post-resolution validation
➤ YN0000: ➤ YN0068: │ babel-plugin-relay ➤ dependencies ➤ @babel/runtime: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: ➤ YN0000: └ Completed
➤ YN0000: ➤ YN0000: ┌ Fetch step
➤ YN0000: ➤ YN0000: └ Completed
➤ YN0000: ➤ YN0000: ┌ Link step
➤ YN0000: ➤ YN0073: │ Skipped due to mode=update-lockfile
➤ YN0000: ➤ YN0000: └ Completed
➤ YN0000: ➤ YN0000: Done with warnings in 0s 457ms
➤ YN0000: 
➤ YN0000: ./index.ts → ./dist...
➤ YN0000: created ./dist in 17.2s
➤ YN0000: app:
➤ YN0000:   assets by status 640 KiB [emitted]
➤ YN0000:     assets by path static/js/*.js 635 KiB
➤ YN0000:       assets by chunk 574 KiB (id hint: vendors)
➤ YN0000:         asset static/js/731.4792c211.js 534 KiB [emitted] [immutable] [minimized] (id hint: vendors) 2 related assets
➤ YN0000:         asset static/js/860.b97b415b.js 39.4 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
➤ YN0000:       + 7 assets
➤ YN0000:     asset index.html 4.35 KiB [emitted]
➤ YN0000:     asset assets.json 1.27 KiB [emitted]
➤ YN0000:   assets by status 19 KiB [compared for emit]
➤ YN0000:     assets by path *.png 14.7 KiB
➤ YN0000:       asset logo512.png 9.44 KiB [compared for emit] [from: public/logo512.png] [copied]
➤ YN0000:       asset logo192.png 5.22 KiB [compared for emit] [from: public/logo192.png] [copied]
➤ YN0000:     asset favicon.ico 3.78 KiB [compared for emit] [from: public/favicon.ico] [copied]
➤ YN0000:     asset manifest.json 485 bytes [compared for emit] [from: public/manifest.json] [copied]
➤ YN0000:     asset robots.txt 67 bytes [compared for emit] [from: public/robots.txt] [copied]
➤ YN0000:   Entrypoint main 568 KiB (2.33 MiB) = static/js/runtime-main.8f514298.js 3.66 KiB static/js/731.4792c211.js 534 KiB static/js/main.9310a4e9.js 30.1 KiB 3 auxiliary assets
➤ YN0000:   orphan modules 869 KiB [orphan] 483 modules
➤ YN0000:   runtime modules 8.71 KiB 12 modules
➤ YN0000:   cacheable modules 1.74 MiB
➤ YN0000:     modules by path ../node_modules/ 1.63 MiB 318 modules
➤ YN0000:     modules by path ./ 112 KiB
➤ YN0000:       modules by path ./routes/ 40.6 KiB
➤ YN0000:         ./routes/Home.tsx 1.35 KiB [built] [code generated]
➤ YN0000:         ./routes/AccountSettings.tsx + 2 modules 8.75 KiB [built] [code generated]
➤ YN0000:         + 3 modules
➤ YN0000:       modules by path ./core/ 22.8 KiB
➤ YN0000:         ./core/AuthProvider.tsx + 1 modules 12.2 KiB [built] [code generated]
➤ YN0000:         ./core/history.ts 2.91 KiB [built] [code generated]
➤ YN0000:         ./core/Auth.ts + 4 modules 7.73 KiB [built] [code generated]
➤ YN0000:       ./index.tsx + 22 modules 47.7 KiB [built] [code generated]
➤ YN0000:       ./config.ts 859 bytes [built] [code generated]
➤ YN0000:   app (webpack 5.73.0) compiled successfully in 29679 ms
➤ YN0000: 
➤ YN0000: workers:
➤ YN0000:   asset proxy.js 847 KiB [emitted] (name: main)
➤ YN0000:   orphan modules 1.05 MiB [orphan] 509 modules
➤ YN0000:   runtime modules 884 bytes 4 modules
➤ YN0000:   cacheable modules 903 KiB
➤ YN0000:     modules by path ../node_modules/relay-runtime/ 504 KiB 102 modules
➤ YN0000:     modules by path ../node_modules/react-relay/ 261 KiB 63 modules
➤ YN0000:     modules by path ../node_modules/mime/ 37.5 KiB 4 modules
➤ YN0000:     modules by path ../node_modules/@babel/runtime/ 14.6 KiB 3 modules
➤ YN0000:     modules by path ../node_modules/fbjs/lib/*.js 5.29 KiB 3 modules
➤ YN0000:     modules by path ../node_modules/@cloudflare/kv-asset-handler/dist/*.js 12.5 KiB 2 modules
➤ YN0000:     modules by path ../node_modules/react/ 6.94 KiB
➤ YN0000:       ../node_modules/react/index.js 190 bytes [built] [code generated]
➤ YN0000:       ../node_modules/react/cjs/react.production.min.js 6.75 KiB [built] [code generated]
➤ YN0000:     ./workers/proxy.ts + 42 modules 59.9 KiB [built] [code generated]
➤ YN0000:     ../node_modules/invariant/browser.js 1.36 KiB [built] [code generated]
➤ YN0000:   workers (webpack 5.73.0) compiled successfully in 18813 ms
➤ YN0000: Done in 32s 532ms
```

### Extra note: 

I added the job unlimited argument to the build command too, but I didn't notice much of a difference with the build time. I'm not too sure exactly what rollup is doing or how yarn plugins work, so just FYI that you may want to change some stuff around. Be careful with this pull-request 🌵 .

### CODE REVIEW

**Comment by andrewstec** [comment]
@koistya Don't merge yet. After the build fix, I see this issue with **Error: Cannot find module '../.pnp.cjs'** :

```
➤ YN0000: node:internal/modules/cjs/loader:959
➤ YN0000:   throw err;
➤ YN0000:   ^
➤ YN0000: 
➤ YN0000: Error: Cannot find module '../.pnp.cjs'
➤ YN0000: Require stack:
➤ YN0000: - internal/preload
➤ YN0000:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
➤ YN0000:     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
➤ YN0000:     at Module.require (node:internal/modules/cjs/loader:1028:19)
➤ YN0000:     at Module._preloadModules (node:internal/modules/cjs/loader:1303:12)
➤ YN0000:     at loadPreloadModules (node:internal/bootstrap/pre_execution:583:5)
➤ YN0000:     at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:95:3)
➤ YN0000:     at node:internal/main/run_main_module:7:1 {
➤ YN0000:   code: 'MODULE_NOT_FOUND',
➤ YN0000:   requireStack: [ 'internal/preload' ]
➤ YN0000: }

```

**Comment by andrewstec** [comment]
@koistya Found a fix for the pnp issue. I had to add another line of code to the `.yarnrc.yaml` file to explicitly enable pnp mode now. You will see it in the fourth commit. The build and start commands now work.

**Comment by koistya** [comment]
@andrewstec you can bump Yarn from `4.0.0-rc.6` to `4.0.0-rc.15` (latest) like this:

```bash
$ yarn set version 4.0.0-rc.15
$ yarn install
$ yarn dlx @yarnpkg/sdks@3.0.0-rc.15 vscode
```

Note, that the latest Yarn version (v4) already comes with most plugins, so we can remove workspace plugins from the PR.

**Comment by andrewstec** [comment]
Ah, that makes sense. I used the 'yarn set version latest' command. I see what happened now.

I will close this PR, as it will bring us backwards.

**Pull request closed without merging**
